### PR TITLE
Turn AttData into trait and optimize response encoding

### PR DESCRIPTION
**Pull request by katyo**
I propose refusing AttData enum in favor of AttData trait.
The trait-based solution is quite useful for users which needs own way to access attribute data.
I implemented such trait for byte slices and arrays, static sized values, and tuples of functions.
Also I made many fixes to avoid unnecessary data copying when creating responses.

### CODE REVIEW

**Comment by katyo** [comment]
Solves #7

**Comment by bjoernQ** [comment]
Do you consider this as complete now? Hopefully will get to reviewing this today - latest tomorrow morning

**Comment by katyo** [comment]
@bjoernQ Of course. I tested it with esp32c3-based device.
But I'm not sure, seems notifications still does not work.

**Review by bjoernQ — APPROVED** [review]
LGTM

Thanks for your contribution!

**Pull request merged**
